name: Atualizar Bot na Oracle Cloud

on:
  push:
    branches:
      - main # Quando houver push na versão principal
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy no Servidor Oracle
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ${{ secrets.ORACLE_USER }}
          key: ${{ secrets.ORACLE_SSH_KEY }}
          script: |
            cd ~/bot
            git fetch origin main
            git reset --hard origin/main
            docker compose up -d --build --force-recreate
            docker image prune -f
